/*
 * JS for wow generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '6eccd2d2-4442-4e92-bfd4-9c8dc280a168';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "wow",
    "location": "wow.html"
}];

wow_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'billAmount': 'wow_billAmount',
        'tipPercent': 'wow_tipPercent',
        'tipPercent-0': 'wow_tipPercent-0',
        'mobilebutton_5': 'wow_mobilebutton_5',
        'mobilegrid_6': 'wow_mobilegrid_6',
        'mobilegridcell_7': 'wow_mobilegridcell_7',
        'mobilelabel_11': 'wow_mobilelabel_11',
        'mobilegridcell_8': 'wow_mobilegridcell_8',
        'tipAmount': 'wow_tipAmount',
        'mobilegridcell_9': 'wow_mobilegridcell_9',
        'mobilelabel_14': 'wow_mobilelabel_14',
        'mobilegridcell_10': 'wow_mobilegridcell_10',
        'billTotal': 'wow_billTotal',
        'mobileimage_16': 'wow_mobileimage_16',
        'html_17': 'wow_html_17'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 536px;user-zoom: fixed;max-zoom: 1;min-zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;max-zoom:1;min-zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'wow';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var wow_beforeshow = function() {
            Apperyio.CurrentScreen = "wow";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var wow_onLoad = function() {
            wow_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            wow_deviceEvents();
            wow_windowEvents();
            wow_elementsEvents();
        };

    // screen window events
    var wow_windowEvents = function() {

            $('#wow').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var wow_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var wow_elementsExtraJS = function() {
            // screen (wow) extra code

            /* tipPercent */

            $("#wow_tipPercent").parent().find("a.ui-btn").attr("tabindex", "2");

        };

    // screen elements handler
    var wow_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#wow_mobilecontainer1 [name="mobilebutton_5"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var billAmount = Number(Apperyio("billAmount").val());
                        var tipPercent = Number(Apperyio("tipPercent").val());

                        var tipAmount = billAmount * tipPercent / 100;
                        var totalAmount = billAmount + tipAmount;

                        Apperyio('tipAmount').text('$' + tipAmount.toFixed(2));
                        Apperyio('billTotal').text('$' + totalAmount.toFixed(2));;

                    }
                },
            }, '#wow_mobilecontainer1 [name="mobilebutton_5"]');

        };

    $(document).off("pagebeforeshow", "#wow").on("pagebeforeshow", "#wow", function(event, ui) {
        wow_beforeshow();
    });

    if (runBeforeShow) {
        wow_beforeshow();
    } else {
        wow_onLoad();
    }
};

$(document).off("pagecreate", "#wow").on("pagecreate", "#wow", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    wow_js();
});